package com.duckblade.osrs.sailing.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.ObjectID;

@Getter
@RequiredArgsConstructor
public enum Port
{

	ALDARIN("Aldarin", "ALDRN", 8605, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_ALDARIN),
	ARDOUGNE("Ardougne", "ARDY", 8596, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_ARDOUGNE),
	BRIMHAVEN("Brimhaven", "BRIM", 8595, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_BRIMHAVEN),
	CAIRN_ISLE("Cairn Isle", "CAIRN", 8602, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_CAIRN_ISLE),
	CATHERBY("Catherby", "CATH", 8593, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_CATHERBY),
	CIVITAS_ILLA_FORTIS("Civitas Illa Fortis", "FORTS", 8600, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_CIVITAS_ILLA_FORTIS),
	CORSAIR_COVE("Corsair Cove", "CORSR", 8601, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_CORSAIR_COVE),
	DEEPFIN_POINT("Deepfin Point", "DPFIN", 8613, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_DEEPFIN_POINT),
	ENTRANA("Entrana", "ENTR", 8599, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_ENTRANA),
	ETCETERIA("Etceteria", "ETC", 8611, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_ETCETERIA),
	HOSIDIUS("Hosidius", "HOSDS", 8591, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_HOSIDIUS),
	JATIZSO("Jatizso", "JATIZ", 8614, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_JATIZSO),
	LANDS_END("Lands' End", "LANDS", 8589, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_LANDS_END),
	LUNAR_ISLE("Lunar Isle", "LUNAR", 8618, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_LUNAR_ISLE),
	MUSA_POINT("Musa Point", "MUSA", 8590, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_MUSA_POINT),
	NEITIZNOT("Neitiznot", "NEITZ", 8615, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_NEITIZNOT),
	PISCATORIS("Piscatoris", "PSCTR", 8617, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PISCATORIS),
	PORT_KHAZARD("Port Khazard", "KHZRD", 8597, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_KHAZARD),
	PORT_PISCARILIUS("Port Piscarilius", "PSCRL", 8594, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_PISCARILIUS),
	PORT_ROBERTS("Port Roberts", "ROBRT", 8608, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_ROBERTS),
	PORT_SARIM("Port Sarim", "SARIM", 8597, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_SARIM),
	PORT_TYRAS("Port Tyras", "TYRAS", 8612, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_TYRAS),
	PRIFDDINAS("Prifddinas", "PRIF", 8616, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PRIFDDINAS),
	RED_ROCK("Red Rock", "REDRK", 8609, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_RED_ROCK),
	RELLEKKA("Rellekka", "RELL", 8610, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_RELLEKKA),
	RUINS_OF_UNKAH("Ruins of Unkah", "UNKAH", 8606, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_RUINS_OF_UNKAH),
	SUNSET_COAST("Sunset Coast", "SUNST", 8603, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_SUNSET_COAST),
	THE_PANDEMONIUM("The Pandemonium", "PAND", 8588, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PANDEMONIUM),
	THE_SUMMER_SHORE("The Summer Shore", "SUMMR", 8604, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_THE_SUMMER_SHORE),
	VOID_KNIGHTS_OUTPOST("Void Knights Outpost", "VOID", 8607, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_VOID_KNIGHTS_OUTPOST),
	;

	private final String fullName;
	private final String shortCode;
	private final int dbRowID;
	private final int ledgerTableID;

	public static Port findByID(int id)
	{
		for (Port port : Port.values())
		{
			if (port.getDbRowID() == id)
			{
				return port;
			}
		}

		return null;
	}

	public static Port findByLedgerTableID(int id)
	{
		for (Port port : Port.values())
		{
			if (port.getLedgerTableID() == id)
			{
				return port;
			}
		}
		return null;
	}

	@Override
	public String toString()
	{
		return fullName;
	}
}
